### ISSUE TITLE
Inconsistent use of `.step` internal argument

### ISSUE THREAD

**Issue by echasnovski** [DavisVaughan/slide#10]
I've come here after some investigation of example in [this tweet](https://twitter.com/hnrklndbrg/status/1164794438276669440).

The root of the problem seems to be that inside `slide_index_dbl()` input function is actually evaluated as `.f(.x, ..., .step = .step)`. This is because internally `slide_index_dbl()` calls `slide_index_vec()` [with `.step` argument](https://github.com/DavisVaughan/slide/blob/10eeee615401d41a04884bf249aec86bc971f5f5/R/slide-index.R#L227) but [it doesn't have one in its signature](https://github.com/DavisVaughan/slide/blob/10eeee615401d41a04884bf249aec86bc971f5f5/R/slide-index.R#L152). This leads to `.step` being treated as part of `...`, which in turn means that passed `.f = sum` is evaluated as `sum(.x, .step)`. As `.step` in this example is always 1, output is bigger by 1 than it should be.

**Comment by DavisVaughan** [comment]
Thank you for investigating! I just fixed it
