### ISSUE TITLE
Which version of vctrs are you using?

### ISSUE THREAD

**Issue by AlanFeder** [DavisVaughan/slide#16]
Hi @DavisVaughan  -- thanks for the new package!

I'm trying to run it, and I keep getting an error message, related to `vctrs`:

```
> library(slide)
Error: package or namespace load failed for ‘slide’:
 .onLoad failed in loadNamespace() for 'slide', details:
  call: fun(libname, pkgname)
  error: function 'vec_proxy' not provided by package 'vctrs'
```

You mention in you documentation that 
> "(Just a warning that this uses a custom version of vctrs, which will soon become its development version)."

How do I make sure to use that version?  I tried following the remotes prompts about downloading the correct version of `vctrs`, but it seems not to have worked.

Thanks!

**Comment by DavisVaughan** [comment]
`remotes::install_github("DavisVaughan/slide")` doesnt work for you? i just ininstalled and reinstalled vctrs and slide, ran than, and everything seems okay. the Remote should be set up correctly so that just works

**Comment by AlanFeder** [comment]
Yes -- that worked!  I'm not sure what happened last time, but uninstalling and reinstalling them worked.
